### ISSUE TITLE
Wait for Exit checkbox trimmed in Bash Command form

### ISSUE THREAD

**Issue by Vanerio** [ForkIssues/TrackerWin#2576]
Hi,
When editing a custom Bash command, the 'Wait for Exit' checkbox is cut off."
Just a tiny visual bug.
 
![Image](https://github.com/user-attachments/assets/ab0ca050-8efa-4d69-9658-0ac0a7915c9a)
 
Thank you!

**Comment by DanPristupov** [comment]
What Fork version do you use? This problem was fixed in Fork 2.6 (https://github.com/fork-dev/TrackerWin/issues/2361)

**Comment by Vanerio** [comment]
> What Fork version do you use? This problem was fixed in Fork 2.6 ([#2361](https://github.com/fork-dev/TrackerWin/issues/2361))

v2.11.1.0

**Comment by TanyaPristupova** [comment]
Do you still have this problem? It looks correct for us (Fork 2.15.3).

<img width="942" height="490" alt="Image" src="https://github.com/user-attachments/assets/5b2b0268-a4a4-4477-85b9-a2bef337c4c4" />

**Comment by Vanerio** [comment]
Yes! Still happening for me in v2.15.3

<img width="995" height="223" alt="Image" src="https://github.com/user-attachments/assets/c8c7e596-c298-458c-a849-47fcf8c4864c" />
