### ISSUE TITLE
[Bug] Floating buttons stay on the screen

### ISSUE THREAD

**Issue by sobkowicz** [ForkIssues/TrackerWin#45]
OS: Windows 10 (v 1803)
Fork Version: 1.23.5.0

Stage and Discard buttons are outside of the window, they are stuck in the same position all the time.

![fork_bug_floating_buttons](https://user-images.githubusercontent.com/5155180/48826774-990f4b00-ed6b-11e8-9ca8-6ae8b1d1f422.png)

**Comment by DanPristupov** [comment]
Hi. How many monitors do you have? What resolution, what DPI?

Do I understand correctly, that the buttons are *always* there and never in the correct place?

**Comment by Otiel** [comment]
I also encounter this issue: if you move your cursor out of the chunk area while it was over one of those two buttons, sometimes those buttons don't disappear. Then, if you resize or move the Fork window, the buttons stay at the same place.

See this video:
![video](https://user-images.githubusercontent.com/3851902/49587300-be9f7580-f963-11e8-9857-0afcd54857c1.gif)

_2 monitors, DPI 100%, 1920x1080_

**Comment by jerone** [comment]
I can confirm this issue. 1 monitor; 1920 x 1080, DPI 100%.

**Comment by orkisz** [comment]
Also confirming the issue. 3 monitors, 1920x1080, DPI 125%

**Comment by sm-g** [comment]
same issue when I'm hovering buttons and then switch by ctrl+2 to list of commits
![2019-01-27_14-28-27](https://user-images.githubusercontent.com/7280273/51800460-00e88300-2240-11e9-8f65-e7acc8a934bf.gif)

**Comment by DanPristupov** [comment]
I made many improvements in 1.29. Please check for updates. Hopefully the problem is fixed.

**Comment by Otiel** [comment]
* I've been able to reproduce the issue shown [here](https://github.com/ForkIssues/TrackerWin/issues/45#issuecomment-444871848) when moving the cursor out of the chunk area.
* I haven't been able to reproduce the issue shown [here](https://github.com/ForkIssues/TrackerWin/issues/45#issuecomment-457909783) when clicking <kbd>Ctrl</kbd><kbd>2</kbd>. 👍

**Comment by DanPristupov** [comment]
@Otiel thank you.

Is it still annoying or not? I think I solved the real problem. Moving cursor out of the chunk area can keep buttons visible, but they will not remain topmost after window deactivation.

**Comment by jerone** [comment]
Also I can still reproduce [this](https://github.com/ForkIssues/TrackerWin/issues/45#issuecomment-444871848), but to be honest it took me a while to get it happening again.

**Comment by Otiel** [comment]
No it's not annoying and I could perfectly live with it. As @jerone said, it doesn't happen often, even when you try to force it to happen.

**Comment by sm-g** [comment]
Another issue during scrolling - buttons may overflow other controls:

![Fork_2019-05-29_16-48-50](https://user-images.githubusercontent.com/7280273/58867037-6bb03c00-86c2-11e9-9bef-76f50df48063.png)

**Comment by DanPristupov** [comment]
@sm-g does this happen in side-by-side diff? Side-by-side diff has a new floating buttons control which will be used everywhere later.

**Comment by sm-g** [comment]
@DanPristupov 
there is other issue (border)
![Fork_2019-06-10_19-35-01](https://user-images.githubusercontent.com/7280273/59210717-e1cb0c00-8bb6-11e9-8ba6-aec94f8ccc50.png)
