### ISSUE TITLE
[Feature Request] SSH key per repository

### ISSUE THREAD

**Issue by myanko** [ForkIssues/TrackerWin#977]
Add an option like for the Use global git credentials, but for SSH keys as users may use multiple servers with different keys.

**Comment by cakeslice** [comment]
Yes please! I'm tired of switching between keys :(

**Comment by DanPristupov** [comment]
You can configure system ssh agent to use multiple ssh keys:

- switch Fork to default system configuration
- open terminal (Ctrl+Alt+T)
- add each of your keys: `ssh-add ~/.ssh/id_rsa`

**Comment by cakeslice** [comment]
Yes you can but there should always be an option in Fork that doesn't depend on the system just like the built-in git.

The option to use SSH keys in fork is great because you don't need to install an ssh agent and add the keys in the terminal. It just needs this extra feature for people that use multiple keys.

I think that is the whole point of Fork, convenience.

**Comment by Stanzilla** [comment]
Ideally something like Tower's account feature where you can assign a gpg and ssh key to a profile and then use those profiles for repositories. I wish I could solve this via git's includeIf config but it doesn't work very with WSL on Windows.

**Comment by DanPristupov** [comment]
Starting from Fork 1.57 you can use multiple SSH keys. This should solve the problem with multiple servers with different keys.

**Comment by Stanzilla** [comment]
How does Fork decide which key to use?

**Comment by DanPristupov** [comment]
@Stanzilla SSH-agent handles this. I guess it sends both public keys, which is fine.

**Comment by cakeslice** [comment]
I still can't get this to work, when multiple keys are selected it says "You can't use multiple keys on the same server"

So how can I specify which server gets each key?

**Comment by Stanzilla** [comment]
Yeah I still have to manually change my git config as well every time I switch from work to personal account and vice versa. It's also confusing that you can't add a second GitHub account in "Accounts". I would love to just be able to use the Fork accounts feature, add my two github accounts, assign them an SSH and GPG key each and for Fork to handle the rest.

**Comment by tmbarker** [comment]
Bump, I have the same issue. To resolve it I had to configure my global **_gitconfig_**, and then some specific repo **_gitconfigs_** to explicitly use a given SSH identity.

**Comment by etienne582** [comment]
+1 that would be awsome !
